ARG PHP_VERSION=8.4
FROM php:${PHP_VERSION}-cli-alpine

RUN apk add --no-cache \
    mpdecimal-dev \
    gcc \
    make \
    autoconf \
    libc-dev

WORKDIR /ext-decimal

COPY . .

RUN phpize --clean > /dev/null 2>&1 || true \
    && phpize \
    && ./configure \
    && make -j$(nproc) \
    && make install

CMD ["make", "test", "TESTS=tests", "NO_INTERACTION=1", "REPORT_EXIT_STATUS=1"]
